"""remove term column

Revision ID: 299f5a23a872
Revises: 5c6cd2a4fd3e
Create Date: 2026-07-21 06:58:47.505455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299f5a23a872'
down_revision: Union[str, Sequence[str], None] = '5c6cd2a4fd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'term')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
