"""removed status column

Revision ID: 540ce95b4fe0
Revises: 299f5a23a872
Create Date: 2026-07-21 07:10:28.874473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ce95b4fe0'
down_revision: Union[str, Sequence[str], None] = '299f5a23a872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
