"""page_number -> nullable

Revision ID: 927652541d9f
Revises: e07115d8d0e0
Create Date: 2026-07-21 19:15:41.054536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927652541d9f'
down_revision: Union[str, Sequence[str], None] = 'e07115d8d0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
