"""remove page count column

Revision ID: 9c79b3fb4280
Revises: 540ce95b4fe0
Create Date: 2026-07-21 07:17:06.670883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c79b3fb4280'
down_revision: Union[str, Sequence[str], None] = '540ce95b4fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
