"""added p[rice

Revision ID: f2cc0edec8f7
Revises: 122dedebb8b7
Create Date: 2026-07-24 21:03:25.893680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cc0edec8f7'
down_revision: Union[str, Sequence[str], None] = '122dedebb8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_types', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('premium_types', sa.Column('max_input_tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_types', 'max_input_tokens')
    op.drop_column('premium_types', 'price')
    # ### end Alembic commands ###
